### ISSUE TITLE
DistributedFeatureConv3d fails for 8 or more workers

### ISSUE THREAD

**Issue by jmerizia** [distdl/distdl#181]
There's a bug with [DistributedFeatureConv3d](https://distdl.readthedocs.io/en/latest/_modules/distdl/nn/conv_feature.html#DistributedFeatureConv3d) layer such that for 8 or more workers, an MPI error message is thrown. This was tested using hydra 3.3 on Ubuntu 18.04 (bionic). This error happens in Python 3.6, 3.7, and 3.8. This does not happen for any version of Python running in Open MPI. This doesn't occur for the DistributedFeatureConv2d nor DistributedFeatureConv1d layers (even for >= 8 workers). The shape of the partition doesn't seem to matter. Also, this was tested on the most recent version of master, which happens to be [fe2de36](https://github.com/distdl/distdl/commit/fe2de3681beb4b083cf54e9ec664225c88d1378a), but the issue may have existed before this.

Here's a working example to reproduce the error:

```python
# example.py
import numpy as np
import torch
from mpi4py import MPI

from distdl.backends.mpi.partition import MPIPartition
from distdl.nn.conv_feature import DistributedFeatureConv3d
from distdl.nn.transpose import DistributedTranspose
from distdl.utilities.torch import zero_volume_tensor

workers = 8

P_world = MPIPartition(MPI.COMM_WORLD)
P_root_base = P_world.create_partition_inclusive(np.arange(1))
P_x_base = P_world.create_partition_inclusive(np.arange(workers))
P_root = P_root_base.create_cartesian_topology_partition([1, 1, 1, 1, 1])
P_x = P_x_base.create_cartesian_topology_partition([1, 1, 1, 1, workers])

x_global_shape = [10, 3, 5, 5, 100]

scatter = DistributedTranspose(P_root, P_x)
layer = DistributedFeatureConv3d(P_x, None, x_global_shape[1], 10, 5)

if P_root.active:
    x = torch.rand(x_global_shape, dtype=torch.float32)
else:
    x = zero_volume_tensor()

x = scatter(x)
y = layer(x)  # error here
```

When executed with the command `mpirun -np 8 python -m mpi4py example.py`,
the above code produces the following error message:

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/jacob/py38/lib/python3.8/site-packages/mpi4py/__main__.py", line 7, in <module>
    main()
  File "/home/jacob/py38/lib/python3.8/site-packages/mpi4py/run.py", line 196, in main
    run_command_line(args)
  File "/home/jacob/py38/lib/python3.8/site-packages/mpi4py/run.py", line 47, in run_command_line
    run_path(sys.argv[0], run_name='__main__')
  File "/usr/lib/python3.8/runpy.py", line 262, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/usr/lib/python3.8/runpy.py", line 95, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "example.py", line 29, in <module>
    y = layer(x)  # error here
  File "/home/jacob/py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/jacob/git/distdl/src/distdl/nn/conv_feature.py", line 267, in forward
    w = self.w_broadcast(self.weight)
  File "/home/jacob/py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/jacob/git/distdl/src/distdl/nn/broadcast.py", line 206, in forward
    return Function.apply(input,
  File "/home/jacob/git/distdl/src/distdl/backends/mpi/autograd/broadcast.py", line 123, in forward
    req.Wait()
  File "mpi4py/MPI/Request.pyx", line 37, in mpi4py.MPI.Request.Wait
mpi4py.MPI.Exception: Other MPI error, error stack:
PMPI_Wait(203).................: MPI_Wait(request=0x7f265cb71200, status=0x1) failed
MPIR_Wait_impl(100)............: 
MPIDU_Sched_progress_state(961): Invalid communicator
```

These are the build details for mpich:

```
HYDRA build details:
    Version:                                 3.3a2
    Release Date:                            Sun Nov 13 09:12:11 MST 2016
    CC:                              gcc   -Wl,-Bsymbolic-functions -Wl,-z,relro 
    CXX:                             g++   -Wl,-Bsymbolic-functions -Wl,-z,relro 
    F77:                             gfortran  -Wl,-Bsymbolic-functions -Wl,-z,relro 
    F90:                             gfortran  -Wl,-Bsymbolic-functions -Wl,-z,relro 
    Configure options:                       '--disable-option-checking' '--prefix=/usr' '--build=x86_64-linux-gnu' '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--sysconfdir=/etc' '--localstatedir=/var' '--disable-silent-rules' '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' '--disable-maintainer-mode' '--disable-dependency-tracking' '--with-libfabric' '--enable-shared' '--enable-fortran=all' '--disable-rpath' '--disable-wrapper-rpath' '--sysconfdir=/etc/mpich' '--libdir=/usr/lib/x86_64-linux-gnu' '--includedir=/usr/include/mpich' '--docdir=/usr/share/doc/mpich' '--with-hwloc-prefix=system' '--enable-checkpointing' '--with-hydra-ckpointlib=blcr' 'CPPFLAGS= -Wdate-time -D_FORTIFY_SOURCE=2 -I/build/mpich-O9at2o/mpich-3.3~a2/src/mpl/include -I/build/mpich-O9at2o/mpich-3.3~a2/src/mpl/include -I/build/mpich-O9at2o/mpich-3.3~a2/src/openpa/src -I/build/mpich-O9at2o/mpich-3.3~a2/src/openpa/src -D_REENTRANT -I/build/mpich-O9at2o/mpich-3.3~a2/src/mpi/romio/include' 'CFLAGS= -g -O2 -fdebug-prefix-map=/build/mpich-O9at2o/mpich-3.3~a2=. -fstack-protector-strong -Wformat -Werror=format-security -O2' 'CXXFLAGS= -g -O2 -fdebug-prefix-map=/build/mpich-O9at2o/mpich-3.3~a2=. -fstack-protector-strong -Wformat -Werror=format-security -O2' 'FFLAGS= -g -O2 -fdebug-prefix-map=/build/mpich-O9at2o/mpich-3.3~a2=. -fstack-protector-strong -O2' 'FCFLAGS= -g -O2 -fdebug-prefix-map=/build/mpich-O9at2o/mpich-3.3~a2=. -fstack-protector-strong -O2' 'build_alias=x86_64-linux-gnu' 'MPICHLIB_CFLAGS=-g -O2 -fdebug-prefix-map=/build/mpich-O9at2o/mpich-3.3~a2=. -fstack-protector-strong -Wformat -Werror=format-security' 'MPICHLIB_CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'MPICHLIB_CXXFLAGS=-g -O2 -fdebug-prefix-map=/build/mpich-O9at2o/mpich-3.3~a2=. -fstack-protector-strong -Wformat -Werror=format-security' 'MPICHLIB_FFLAGS=-g -O2 -fdebug-prefix-map=/build/mpich-O9at2o/mpich-3.3~a2=. -fstack-protector-strong' 'MPICHLIB_FCFLAGS=-g -O2 -fdebug-prefix-map=/build/mpich-O9at2o/mpich-3.3~a2=. -fstack-protector-strong' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro' 'FC=gfortran' 'F77=gfortran' 'MPILIBNAME=mpich' '--cache-file=/dev/null' '--srcdir=.' 'CC=gcc' 'LIBS=' 'MPLLIBNAME=mpl'
    Process Manager:                         pmi
    Launchers available:                     ssh rsh fork slurm ll lsf sge manual persist
    Topology libraries available:            hwloc
    Resource management kernels available:   user slurm ll lsf sge pbs cobalt
    Checkpointing libraries available:       blcr
    Demux engines available:                 poll select
```

**Comment by rhewett** [comment]
Changing the definition of the layer to

   layer = DistributedFeatureConv3d(P_x, x_global_shape[1], 10, 5)

seems to fix this.  What is the `None` meant to represent in your example?

Otherwise I cannot replicate this.
